#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

REDIS_CONF="${REDIS_CONF:-/etc/redis.conf}";
REDIS__dir="${REDIS__dir:-/var/lib/redis}";

# setup directories
vecho "Ensure configuration directories exist.";
mkdir -p \
    $(dirname ${REDIS_CONF}) \
    "${REDIS__dir}" \
    ;

# ensure redis conf exists
if [ ! -f "${REDIS_CONF}" ];
then
    vecho "Setting up default configuration as ${REDIS_CONF}";
    cp /defaults/redis.conf ${REDIS_CONF};

    # update redis configuration from environment vars i.e. /run/s6/container_environment/REDIS__<varname> (double underscores)
    # only if custom configuration does not exist
    if find /run/s6/container_environment/REDIS__* -maxdepth 1 > /dev/null 2>&1; then
        for FILENAME in /run/s6/container_environment/*;
        do
            if [[ "${FILENAME##*/}" == "REDIS__"* ]];
            then
                BASENAME="${FILENAME##*/}";
                VAR=${BASENAME//REDIS__/};
                VAL="$(cat ${FILENAME})";
                sed -i -e "s|^#\? \?${VAR} .*\$|$VAR $VAL|" ${REDIS_CONF};
                echo "Set ${VAR} from ${BASENAME} in ${REDIS_CONF}";
            fi;
        done;
    fi;
fi;

# REDIS__logfile="${REDIS__logfile:-}";
# ensure logfile exists if logfile is set e.g "/var/log/redis/redis_6379.log"
if [ -n "${REDIS__logfile}" ] \
&& [ ! -f "${REDIS__logfile}" ];
then
    fp="${REDIS__logfile}";
    vecho "Ensure logfile exists: ${fp}";
    mkdir -p $(dirname $fp);
    touch $fp;
    if [ "X${EUID}" == "X0" ]; # requires root
    then
        chown -R ${S6_USER:-alpine}:${PGID:-1000} \
            $(dirname $fp) \
            $fp \
            ;
    fi;
fi;

REDIS__pidfile="${REDIS__pidfile:-/var/run/redis.pid}";
if [ ! -f "${REDIS__pidfile}" ];
then
    vecho "Ensure redis pid-file exists: ${REDIS__pidfile}";
    touch ${REDIS__pidfile};
fi;

# fix permissions
if [ -z "${REDIS_SKIP_PERMFIX}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions.";
    chown -R ${S6_USER:-alpine}:${PGID:-1000} \
        "${REDIS_CONF}" \
        "${REDIS__dir}" \
        "${REDIS__pidfile}" \
        ;
fi;
