#!/usr/bin/with-contenv bash
set -e

usercmd () { if [ "X${EUID}" != "X0" ]; then ${1} "${@:2}"; else s6-setuidgid ${PUID:-1000}:${PGID:-1000} ${1} "${@:2}"; fi; }

REDIS_CONF="${REDIS_CONF:-/etc/redis.conf}";
REDIS__dir="${REDIS__dir:-/var/lib/redis}";

cd ${REDIS__dir} || exit 1;

REDIS_ARGS="${REDIS_ARGS:- $REDIS_CONF}"

usercmd \
exec \
    redis-server \
    ${REDIS_ARGS} \
    ;
