#!/usr/bin/with-contenv bash
set -e

REDIS_CONF="${REDIS_CONF:-/etc/redis.conf}";
REDIS__dir="${REDIS__dir:-/var/lib/redis}";

cd ${REDIS__dir} || exit 1;

REDIS_ARGS="${REDIS_ARGS:- $REDIS_CONF}"

s6-setuidgid ${S6_USER:-alpine} \
exec \
    redis-server \
    ${REDIS_ARGS} \
    ;
